# Max Gadeberg
# Aug 29, 2024

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from time import sleep

# User credentials
username = ""
password = ""

class TestSNOWBusinessService():
    def setup_method(self, method):
        # Initialize the Firefox WebDriver
        self.driver = webdriver.Firefox()
        self.vars = {}
        print("Setup complete. WebDriver initialized.")

    def teardown_method(self, method):
        # Close the browser after test execution
        self.driver.quit()
        print("Teardown complete. WebDriver closed.")

    def test_sNOWBusinessService(self):
        try:
            # Navigate to the ServiceNow login page
            self.driver.get("https://exampledev.service-now.com/now/nav/ui/classic/params/target/cmdb_ci_service.do%3Fsys_id%3D-1%26sys_is_list%3Dtrue%26sys_target%3Dcmdb_ci_service%26sysparm_checked_items%3D%26sysparm_fixed_query%3D%26sysparm_group_sort%3D%26sysparm_list_css%3D%26sysparm_query%3Dservice_classification%253dBusiness%2BService%26sysparm_referring_url%3Dcmdb_ci_service_list.do%253fsysparm_query%253dservice_classification%25253DBusiness%252bService%25255EEQ%26sysparm_target%3D%26sysparm_view%3D")
            print("Navigated to ServiceNow login page.")

            # Wait for the page to load
            sleep(3)

            # Log in to ServiceNow
            self.driver.find_element(By.ID, "user_name").send_keys(username)
            self.driver.find_element(By.ID, "user_password").send_keys(password)
            self.driver.find_element(By.ID, "sysverb_login").click()
            print("Logged in successfully.")

            # Wait for the login process to complete
            sleep(3)

            # Navigate to the Business Service form
            self.driver.get("https://exampledev.service-now.com/now/nav/ui/classic/params/target/cmdb_ci_service.do%3Fsys_id%3D-1%26sys_is_list%3Dtrue%26sys_target%3Dcmdb_ci_service%26sysparm_checked_items%3D%26sysparm_fixed_query%3D%26sysparm_group_sort%3D%26sysparm_list_css%3D%26sysparm_query%3Dservice_classification%253dBusiness%2BService%26sysparm_referring_url%3Dcmdb_ci_service_list.do%253fsysparm_query%253dservice_classification%25253DBusiness%252bService%25255EEQ%26sysparm_target%3D%26sysparm_view%3D")
            print("Navigated to Business Service form.")

            # Wait for the form to load
            sleep(5)

            # Switch to the correct iframe
            self.driver.switch_to.frame(0)
            print("Switched to the iframe.")

            # Fill out the Business Service form
            self.driver.find_element(By.ID, "cmdb_ci_service.name").send_keys("name/sid")
            self.driver.find_element(By.ID, "cmdb_ci_service.u_csi").send_keys("csi")
            self.driver.find_element(By.ID, "cmdb_ci_service.u_group_sid").send_keys("group_sid")
            self.driver.find_element(By.ID, "sys_display.cmdb_ci_service.parent").send_keys("NG911", Keys.ENTER)
            self.driver.find_element(By.ID, "cmdb_ci_service.u_netsuite_so").send_keys("so#")
            self.driver.find_element(By.ID, "cmdb_ci_service.u_tsp_code").send_keys("code")
            self.driver.find_element(By.ID, "sys_display.cmdb_ci_service.u_paired_service").send_keys("AASD/DMSETH07002289")
            self.driver.find_element(By.ID, "cmdb_ci_service.u_cpe_dns").send_keys("cpe dns")
            
            # Select provider from dropdown
            element = self.driver.find_element(By.CSS_SELECTOR, "#label\\.cmdb_ci_service\\.u_provider .label-text")
            actions = ActionChains(self.driver)
            actions.move_to_element(element).perform()
            self.driver.find_element(By.ID, "sys_display.cmdb_ci_service.u_provider").send_keys("Adva")

            # Select service type from dropdown
            self.driver.find_element(By.ID, "cmdb_ci_service.u_service_type").click()
            dropdown = self.driver.find_element(By.ID, "cmdb_ci_service.u_service_type")
            dropdown.find_element(By.XPATH, "//option[. = 'Cell Carrier']").click()
            
            # Enter other details
            self.driver.find_element(By.ID, "label.ni.cmdb_ci_service.u_dark_fiber").click()
            self.driver.find_element(By.ID, "cmdb_ci_service.comments").send_keys("comments")

            # Select location from dropdown
            element = self.driver.find_element(By.CSS_SELECTOR, "#label\\.cmdb_ci_service\\.location > .col-xs-12")
            actions.move_to_element(element).perform()
            self.driver.find_element(By.ID, "sys_display.cmdb_ci_service.location").send_keys("Omak - OMK - Okanogan PUD COLO")
            
            # Select customer from dropdown
            element = self.driver.find_element(By.CSS_SELECTOR, "#label\\.cmdb_ci_service\\.u_end_user > .col-xs-12")
            actions.move_to_element(element).perform()
            self.driver.find_element(By.ID, "sys_display.cmdb_ci_service.u_customer").send_keys("Adva", Keys.ENTER)

            # Enter end user details and other fields
            self.driver.find_element(By.ID, "cmdb_ci_service.u_end_user").send_keys("end_user")
            self.driver.find_element(By.ID, "cmdb_ci_service.operational_status").click()
            self.driver.find_element(By.CSS_SELECTOR, "#cmdb_ci_service\\.operational_status > option:nth-child(1)").click()
            self.driver.find_element(By.ID, "cmdb_ci_service.u_nn_commit_rate").send_keys("commit_rate")
            self.driver.find_element(By.ID, "cmdb_ci_service.u_eth_vlan").send_keys("eth_vlans")
            self.driver.find_element(By.ID, "cmdb_ci_service.u_ocular_alias").send_keys("alias")
            self.driver.find_element(By.ID, "cmdb_ci_service.u_mep_devices").send_keys("devices")
            
            # Submit the form
            self.driver.find_element(By.ID, "sysverb_insert_bottom").click()
            print("Form submitted successfully.")

            # Success message
            print("✅ Test completed successfully. All actions performed and form submitted")

        except Exception as e:
            # Print error if something goes wrong
            print(f"❌ An error occurred: {e}")
